### ISSUE TITLE
Have issue to read command "^" and "C", and if the note have space it will error.

### ISSUE THREAD

**Issue by FeiZhaixiage** [Neskol/MaiLib#26]
### for "^" issue:
def of "^" command:

> ">", "<", "^" ... Arc shape
> Connects the start to the end along the circled judgment line.
> If the direction of travel is to the right, use ">". If left, use "<".
> If the distance is shorter than half the circle, "^" can be used and thinking of the direction is thus not needed.

### for "C" issue:
it will crash when I write C note in shimai file.
e.g.:
8x/C

### for space issue:
if my chart have space in command.
e.g.:
{8}, , 8^6v4b[8:3], ,,, ,,

These issue is from Simaiparser.cs
My coding is not very good. I only can give u some code suggestion, can not fork and pull. Sorry about that.

**Comment by FeiZhaixiage** [comment]
and for code suggestion:
### for "^" issue:
`public Slide SlideOfToken(string token, int bar, int tick, Note slideStart, double bpm){}`
```
else if (token.Contains("^"))
{
    endKeyCandidate = token.Substring(1, 1);
    sustainSymbol = token.IndexOf("[");
    sustainCandidate = token.Substring(sustainSymbol + 1).Split("]")[0]; //sustain candidate is like 1:2
    if (PreviousSlideStart.Key.Equals("0") ||
        PreviousSlideStart.Key.Equals("1") ||
        PreviousSlideStart.Key.Equals("6") ||
        PreviousSlideStart.Key.Equals("7"))
        noteType = NoteType.SCR;
    else noteType = NoteType.SCL;
    // noteType = NoteType.SCR;
}
```
I just copy code from ">" command, so it need more code that can be correct.


### for "C" issue:
`public Tap TapOfToken(string token, int bar, int tick, double bpm){}`
```
if (isTouch)
{
    var hasSpecialEffect = token.Contains("f");
    var keyCandidate = 0;
    if (token == "C")
    {
        keyCandidate = 0;
    }
    else
    {
        keyCandidate = int.Parse(token.Substring(1, 1)) - 1;
    }
    result = new Tap(NoteType.TTP, bar, tick, keyCandidate + token.Substring(0, 1), hasSpecialEffect, "M1");
}
```

**Comment by Neskol** [comment]
Thank you for reporting the bug! Indeed those are unsupported Simai grammar and it will be fixed in next PR. Some of the Simai features are also not supported like `@`, `[bpm#quaver:multiple]`.

**Comment by Neskol** [comment]
Confirmed: `^` is a short hand for   SCL/SCR and requires different `KeyNum` and `EndKeyNum`. `^` slide also requires `| KeyNum - EndKeyNum | != 4`.
Also Simai wiki does not require space compatibility but it will still be added in the next PR. Would not recommended write space in between commas.
